export const irregularVerbsGame = {
  name: 'Irregular Verbs',
  instructions: 'Translate the verb into all tenses.',
  actions: [
    {
      type: 'text',
      placeholder: 'Infinitive',
      label: 'Infinitive'
    },
    {
      type: 'text',
      placeholder: 'Past',
      label: 'Past'
    },
    {
      type: 'text',
      placeholder: 'Participle',
      label: 'Participle'
    }
  ],
  questions: [
    { prompt: 'surgir', answers: [{ value: 'arise' }, { value: 'arose' }, { value: 'arisen' }] },
    { prompt: 'despertarse', answers: [{ value: 'awake' }, { value: 'awoke' }, { value: 'awoken' }] },
    { prompt: 'ser', answers: [{ value: 'be' }, { value: 'was' }, { value: 'been' }] },
    { prompt: 'estar', answers: [{ value: 'be' }, { value: 'were' }, { value: 'been' }] },
    { prompt: 'soportar', answers: [{ value: 'bear' }, { value: 'bore' }, { value: 'born' }] },
    { prompt: 'vencer', answers: [{ value: 'beat' }, { value: 'beat' }, { value: 'beaten' }] },
    { prompt: 'llegar a ser', answers: [{ value: 'become' }, { value: 'became' }, { value: 'become' }] },
    { prompt: 'empezar', answers: [{ value: 'begin' }, { value: 'began' }, { value: 'begun' }] },
    { prompt: 'doblar', answers: [{ value: 'bend' }, { value: 'bent' }, { value: 'bent' }] },
    { prompt: 'apostar', answers: [{ value: 'bet' }, { value: 'bet' }, { value: 'bet' }] },
    { prompt: 'atar', answers: [{ value: 'bind' }, { value: 'bound' }, { value: 'bound' }] },
    { prompt: 'pujar', answers: [{ value: 'bid' }, { value: 'bid' }, { value: 'bid' }] },
    { prompt: 'morder', answers: [{ value: 'bite' }, { value: 'bit' }, { value: 'bitten' }] },
    { prompt: 'sangrar', answers: [{ value: 'bleed' }, { value: 'bled' }, { value: 'bled' }] },
    { prompt: 'soplar', answers: [{ value: 'blow' }, { value: 'blew' }, { value: 'blown' }] },
    { prompt: 'romper', answers: [{ value: 'break' }, { value: 'broke' }, { value: 'broken' }] },
    { prompt: 'criar', answers: [{ value: 'breed' }, { value: 'bred' }, { value: 'bred' }] },
    { prompt: 'traer', answers: [{ value: 'bring' }, { value: 'brought' }, { value: 'brought' }] },
    { prompt: 'radiar', answers: [{ value: 'broadcast' }, { value: 'broadcast' }, { value: 'broadcast' }] },
    { prompt: 'construir', answers: [{ value: 'build' }, { value: 'built' }, { value: 'built' }] },
    { prompt: 'quemar', answers: [{ value: 'burn' }, { value: 'burnt' }, { value: 'burnt' }] },
    { prompt: 'reventar', answers: [{ value: 'burst' }, { value: 'burst' }, { value: 'burst' }] },
    { prompt: 'comprar', answers: [{ value: 'buy' }, { value: 'bought' }, { value: 'bought' }] },
    { prompt: 'atrapar', answers: [{ value: 'catch' }, { value: 'caught' }, { value: 'caught' }] },
    { prompt: 'venir', answers: [{ value: 'come' }, { value: 'came' }, { value: 'come' }] },
    { prompt: 'costar', answers: [{ value: 'cost' }, { value: 'cost' }, { value: 'cost' }] },
    { prompt: 'cortar', answers: [{ value: 'cut' }, { value: 'cut' }, { value: 'cut' }] },
    { prompt: 'elegir', answers: [{ value: 'choose' }, { value: 'chose' }, { value: 'chosen' }] },
    { prompt: 'agarrarse', answers: [{ value: 'cling' }, { value: 'clung' }, { value: 'clung' }] },
    { prompt: 'arrastrarse', answers: [{ value: 'creep' }, { value: 'crept' }, { value: 'crept' }] },
    { prompt: 'tratar', answers: [{ value: 'deal' }, { value: 'dealt' }, { value: 'dealt' }] },
    { prompt: 'cavar', answers: [{ value: 'dig' }, { value: 'dug' }, { value: 'dug' }] },
    { prompt: 'hacer', answers: [{ value: 'do' }, { value: 'did' }, { value: 'done' }] },
    { prompt: 'dibujar', answers: [{ value: 'draw' }, { value: 'drew' }, { value: 'drawn' }] },
    { prompt: 'soñar', answers: [{ value: 'dream' }, { value: 'dreamt' }, { value: 'dreamt' }] },
    { prompt: 'beber', answers: [{ value: 'drink' }, { value: 'drank' }, { value: 'drunk' }] },
    { prompt: 'conducir', answers: [{ value: 'drive' }, { value: 'drove' }, { value: 'driven' }] },
    { prompt: 'comer', answers: [{ value: 'eat' }, { value: 'ate' }, { value: 'eaten' }] },
    { prompt: 'caer', answers: [{ value: 'fall' }, { value: 'fell' }, { value: 'fallen' }] },
    { prompt: 'alimentar', answers: [{ value: 'feed' }, { value: 'fed' }, { value: 'fed' }] },
    { prompt: 'sentir', answers: [{ value: 'feel' }, { value: 'felt' }, { value: 'felt' }] },
    { prompt: 'luchar', answers: [{ value: 'fight' }, { value: 'fought' }, { value: 'fought' }] },
    { prompt: 'encontrar', answers: [{ value: 'find' }, { value: 'found' }, { value: 'found' }] },
    { prompt: 'huir', answers: [{ value: 'flee' }, { value: 'fled' }, { value: 'fled' }] },
    { prompt: 'volar', answers: [{ value: 'fly' }, { value: 'flew' }, { value: 'flown' }] },
    { prompt: 'prohibir', answers: [{ value: 'forbid' }, { value: 'forbade' }, { value: 'forbidden' }] },
    { prompt: 'olvidar', answers: [{ value: 'forget' }, { value: 'forgot' }, { value: 'forgotten' }] },
    { prompt: 'perdonar', answers: [{ value: 'forgive' }, { value: 'forgave' }, { value: 'forgiven' }] },
    { prompt: 'congelar', answers: [{ value: 'freeze' }, { value: 'froze' }, { value: 'frozen' }] },
    { prompt: 'obtener', answers: [{ value: 'get' }, { value: 'got' }, { value: 'got' }] },
    { prompt: 'dar', answers: [{ value: 'give' }, { value: 'gave' }, { value: 'given' }] },
    { prompt: 'ir', answers: [{ value: 'go' }, { value: 'went' }, { value: 'gone' }] },
    { prompt: 'crecer', answers: [{ value: 'grow' }, { value: 'grew' }, { value: 'grown' }] },
    { prompt: 'moler', answers: [{ value: 'grind' }, { value: 'ground' }, { value: 'ground' }] },
    { prompt: 'colgar', answers: [{ value: 'hang' }, { value: 'hung' }, { value: 'hung' }] },
    { prompt: 'haber/tener', answers: [{ value: 'have' }, { value: 'had' }, { value: 'had' }] },
    { prompt: 'oir', answers: [{ value: 'hear' }, { value: 'heard' }, { value: 'heard' }] },
    { prompt: 'ocultar', answers: [{ value: 'hide' }, { value: 'hid' }, { value: 'hidden' }] },
    { prompt: 'golpear', answers: [{ value: 'hit' }, { value: 'hit' }, { value: 'hit' }] },
    { prompt: 'sostener', answers: [{ value: 'hold' }, { value: 'held' }, { value: 'held' }] },
    { prompt: 'herir', answers: [{ value: 'hurt' }, { value: 'hurt' }, { value: 'hurt' }] },
    { prompt: 'guardar', answers: [{ value: 'keep' }, { value: 'kept' }, { value: 'kept' }] },
    { prompt: 'know', answers: [{ value: 'know' }, { value: 'knew' }, { value: 'known' }] },
    { prompt: 'kneel', answers: [{ value: 'kneel' }, { value: 'knelt' }, { value: 'knelt' }] },
    { prompt: 'knit', answers: [{ value: 'knit' }, { value: 'knit' }, { value: 'knit' }] },
    { prompt: 'lay', answers: [{ value: 'lay' }, { value: 'laid' }, { value: 'laid' }] },
    { prompt: 'lead', answers: [{ value: 'lead' }, { value: 'led' }, { value: 'led' }] },
    { prompt: 'lean', answers: [{ value: 'lean' }, { value: 'leant' }, { value: 'leant' }] },
    { prompt: 'leap', answers: [{ value: 'leap' }, { value: 'leapt' }, { value: 'leapt' }] },
    { prompt: 'learn', answers: [{ value: 'learn' }, { value: 'learnt' }, { value: 'learnt' }] },
    { prompt: 'leave', answers: [{ value: 'leave' }, { value: 'left' }, { value: 'left' }] },
    { prompt: 'lend', answers: [{ value: 'lend' }, { value: 'lent' }, { value: 'lent' }] },
    { prompt: 'let', answers: [{ value: 'let' }, { value: 'let' }, { value: 'let' }] },
    { prompt: 'lie', answers: [{ value: 'lie' }, { value: 'lay' }, { value: 'lain' }] },
    { prompt: 'light', answers: [{ value: 'light' }, { value: 'lit' }, { value: 'lit' }] },
    { prompt: 'lose', answers: [{ value: 'lose' }, { value: 'lost' }, { value: 'lost' }] },
    { prompt: 'make', answers: [{ value: 'make' }, { value: 'made' }, { value: 'made' }] },
    { prompt: 'mean', answers: [{ value: 'mean' }, { value: 'meant' }, { value: 'meant' }] },
    { prompt: 'meet', answers: [{ value: 'meet' }, { value: 'met' }, { value: 'met' }] },
    { prompt: 'mistake', answers: [{ value: 'mistake' }, { value: 'mistook' }, { value: 'mistaken' }] },
    { prompt: 'overcome', answers: [{ value: 'overcome' }, { value: 'overcame' }, { value: 'overcome' }] },
    { prompt: 'pay', answers: [{ value: 'pay' }, { value: 'paid' }, { value: 'paid' }] },
    { prompt: 'put', answers: [{ value: 'put' }, { value: 'put' }, { value: 'put' }] },
    { prompt: 'read', answers: [{ value: 'read' }, { value: 'read' }, { value: 'read' }] },
    { prompt: 'ride', answers: [{ value: 'ride' }, { value: 'rode' }, { value: 'ridden' }] },
    { prompt: 'ring', answers: [{ value: 'ring' }, { value: 'rang' }, { value: 'rung' }] },
    { prompt: 'rise', answers: [{ value: 'rise' }, { value: 'rose' }, { value: 'risen' }] },
    { prompt: 'run', answers: [{ value: 'run' }, { value: 'ran' }, { value: 'run' }] },
    { prompt: 'say', answers: [{ value: 'say' }, { value: 'said' }, { value: 'said' }] },
    { prompt: 'see', answers: [{ value: 'see' }, { value: 'saw' }, { value: 'seen' }] },
    { prompt: 'seek', answers: [{ value: 'seek' }, { value: 'sought' }, { value: 'sought' }] },
    { prompt: 'sell', answers: [{ value: 'sell' }, { value: 'sold' }, { value: 'sold' }] },
    { prompt: 'send', answers: [{ value: 'send' }, { value: 'sent' }, { value: 'sent' }] },
    { prompt: 'set', answers: [{ value: 'set' }, { value: 'set' }, { value: 'set' }] },
    { prompt: 'sew', answers: [{ value: 'sew' }, { value: 'sewed' }, { value: 'sewed' }] },
    { prompt: 'shake', answers: [{ value: 'shake' }, { value: 'shook' }, { value: 'shaken' }] },
    { prompt: 'shear', answers: [{ value: 'shear' }, { value: 'shore' }, { value: 'shorn' }] },
    { prompt: 'shine', answers: [{ value: 'shine' }, { value: 'shone' }, { value: 'shone' }] },
    { prompt: 'shoot', answers: [{ value: 'shoot' }, { value: 'shot' }, { value: 'shot' }] },
    { prompt: 'show', answers: [{ value: 'show' }, { value: 'showed' }, { value: 'shown' }] },
    { prompt: 'shrink', answers: [{ value: 'shrink' }, { value: 'shrank' }, { value: 'shrunk' }] },
    { prompt: 'shut', answers: [{ value: 'shut' }, { value: 'shut' }, { value: 'shut' }] },
    { prompt: 'sing', answers: [{ value: 'sing' }, { value: 'sang' }, { value: 'sung' }] },
    { prompt: 'sink', answers: [{ value: 'sink' }, { value: 'sank' }, { value: 'sunk' }] },
    { prompt: 'sit', answers: [{ value: 'sit' }, { value: 'sat' }, { value: 'sat' }] },
    { prompt: 'sleep', answers: [{ value: 'sleep' }, { value: 'slept' }, { value: 'slept' }] },
    { prompt: 'slide', answers: [{ value: 'slide' }, { value: 'slid' }, { value: 'slid' }] },
    { prompt: 'smell', answers: [{ value: 'smell' }, { value: 'smelt' }, { value: 'smelt' }] },
    { prompt: 'sow', answers: [{ value: 'sow' }, { value: 'sowed' }, { value: 'sowed' }] },
    { prompt: 'speak', answers: [{ value: 'speak' }, { value: 'spoke' }, { value: 'spoken' }] },
    { prompt: 'speed', answers: [{ value: 'speed' }, { value: 'sped' }, { value: 'sped' }] },
    { prompt: 'spell', answers: [{ value: 'spell' }, { value: 'spelt' }, { value: 'spelt' }] },
    { prompt: 'spend', answers: [{ value: 'spend' }, { value: 'spent' }, { value: 'spent' }] },
    { prompt: 'spill', answers: [{ value: 'spill' }, { value: 'spilt' }, { value: 'spilt' }] },
    { prompt: 'spin', answers: [{ value: 'spin' }, { value: 'spun' }, { value: 'spun' }] },
    { prompt: 'spit', answers: [{ value: 'spit' }, { value: 'spat' }, { value: 'spat' }] },
    { prompt: 'split', answers: [{ value: 'split' }, { value: 'split' }, { value: 'split' }] },
    { prompt: 'spoil', answers: [{ value: 'spoil' }, { value: 'spoilt' }, { value: 'spoilt' }] },
    { prompt: 'spread', answers: [{ value: 'spread' }, { value: 'spread' }, { value: 'spread' }] },
    { prompt: 'spring', answers: [{ value: 'spring' }, { value: 'sprang' }, { value: 'sprung' }] },
    { prompt: 'stand', answers: [{ value: 'stand' }, { value: 'stood' }, { value: 'stood' }] },
    { prompt: 'steal', answers: [{ value: 'steal' }, { value: 'stole' }, { value: 'stolen' }] },
    { prompt: 'stick', answers: [{ value: 'stick' }, { value: 'stuck' }, { value: 'stuck' }] },
    { prompt: 'sting', answers: [{ value: 'sting' }, { value: 'stung' }, { value: 'stung' }] },
    { prompt: 'stink', answers: [{ value: 'stink' }, { value: 'stank' }, { value: 'stunk' }] },
    { prompt: 'stride', answers: [{ value: 'stride' }, { value: 'strode' }, { value: 'stridden' }] },
    { prompt: 'strike', answers: [{ value: 'strike' }, { value: 'struck' }, { value: 'struck' }] },
    { prompt: 'swear', answers: [{ value: 'swear' }, { value: 'swore' }, { value: 'sworn' }] },
    { prompt: 'sweat', answers: [{ value: 'sweat' }, { value: 'sweat' }, { value: 'sweat' }] },
    { prompt: 'sweep', answers: [{ value: 'sweep' }, { value: 'swept' }, { value: 'swept' }] },
    { prompt: 'swell', answers: [{ value: 'swell' }, { value: 'swelled' }, { value: 'swollen' }] },
    { prompt: 'swim', answers: [{ value: 'swim' }, { value: 'swam' }, { value: 'swum' }] },
    { prompt: 'swing', answers: [{ value: 'swing' }, { value: 'swung' }, { value: 'swung' }] },
    { prompt: 'take', answers: [{ value: 'take' }, { value: 'took' }, { value: 'taken' }] },
    { prompt: 'teach', answers: [{ value: 'teach' }, { value: 'taught' }, { value: 'taught' }] },
    { prompt: 'tear', answers: [{ value: 'tear' }, { value: 'tore' }, { value: 'torn' }] },
    { prompt: 'tell', answers: [{ value: 'tell' }, { value: 'told' }, { value: 'told' }] },
    { prompt: 'think', answers: [{ value: 'think' }, { value: 'thought' }, { value: 'thought' }] },
    { prompt: 'throw', answers: [{ value: 'throw' }, { value: 'threw' }, { value: 'thrown' }] },
    { prompt: 'thrust', answers: [{ value: 'thrust' }, { value: 'thrust' }, { value: 'thrust' }] },
    { prompt: 'tread', answers: [{ value: 'tread' }, { value: 'trod' }, { value: 'trodden' }] },
    { prompt: 'understand', answers: [{ value: 'understand' }, { value: 'understood' }, { value: 'understood' }] },
    { prompt: 'undergo', answers: [{ value: 'undergo' }, { value: 'underwent' }, { value: 'undergone' }] },
    { prompt: 'undertake', answers: [{ value: 'undertake' }, { value: 'undertook' }, { value: 'undertaken' }] },
    { prompt: 'wake', answers: [{ value: 'wake' }, { value: 'woke' }, { value: 'woken' }] },
    { prompt: 'wear', answers: [{ value: 'wear' }, { value: 'wore' }, { value: 'worn' }] },
    { prompt: 'weave', answers: [{ value: 'weave' }, { value: 'wove' }, { value: 'woven' }] },
    { prompt: 'wet', answers: [{ value: 'wet' }, { value: 'wet' }, { value: 'wet' }] },
    { prompt: 'win', answers: [{ value: 'win' }, { value: 'won' }, { value: 'won' }] },
    { prompt: 'wind', answers: [{ value: 'wind' }, { value: 'wound' }, { value: 'wound' }] },
    { prompt: 'withdraw', answers: [{ value: 'withdraw' }, { value: 'withdrew' }, { value: 'withdrawn' }] },
    { prompt: 'wring', answers: [{ value: 'wring' }, { value: 'wrung' }, { value: 'wrung' }] },
    { prompt: 'write', answers: [{ value: 'write' }, { value: 'wrote' }, { value: 'written' }] }
  ]
}
